version: 2.1

supported-svelte-versions: &supported-svelte-versions ["local", "3.29.4"]

workflows:
  build_and_test:
    jobs:
      - build_and_test:
          matrix:
            parameters:
              svelte-version: *supported-svelte-versions
jobs:
  build_and_test:
    parameters:
      svelte-version:
        type: string
        description: Overrides the Svelte version. `local` refers to the locally-installed version.
        default: "local"
    docker:
      - image: circleci/node:14-buster-browsers
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y fonts-noto-color-emoji
      - run:
          name: Check node version
          command: node -v
      - restore_cache:
          name: Restore yarn cache
          key: yarn-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn install
          command: yarn install --immutable
      - save_cache:
          name: Save yarn cache
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Bundlesize tests
          command: yarn benchmark:bundlesize
      - when:
          condition:
            not:
              equal: [ <<parameters.svelte-version>>, "local" ]
          steps:
            - run:
                name: Override version of svelte@<<parameters.svelte-version>>
                # Do --ignore-scripts because we don't actually want the old version of Svelte to compile
                # the picker; just get injected at runtime. This is how `emoji-picker-element/svelte` is used.
                command: yarn add svelte@<<parameters.svelte-version>> --dev --ignore-scripts
      - run:
          name: Unit tests
          command: yarn test
      - run:
          name: Code coverage tests
          command: yarn cover
      - run:
          name: Leak tests
          command: yarn test:leak
      - store_artifacts:
          path: coverage